baseURL = "https://galerie.kavkaterie.cz/"
languageCode = "en-us"
title = "Ptusek"
theme = ["minimal", "hugo-shortcode-gallery"]
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Pavla Novotná"
    description = "Kavkaterie – galerie"
    githubUsername = "#"
    accent = "grey"
    showBorder = false
    backgroundColor = "white"
    font = "Corinthia Regular" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    css = ["css/custom.css"]

[[menu.main]]
    url = "https://kavkaterie.cz"
    name = "BLOG"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://instagram.com/pavli_novotna"
    name = "fab fa-instagram"
    weight = 1
